version: '3'

services:
 trilium:
    image: 'zadam/trilium:latest'
    container_name: trilium
    restart: unless-stopped
    volumes:
      - "./data:/home/node/trilium-data"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trilium.rule=Host(`${TRAEFIK_TRILIUM}`)"
      - "traefik.http.routers.trilium.entrypoints=https"
      - "traefik.http.routers.trilium.tls=true"
      - "traefik.http.routers.trilium.tls.certresolver=mydnschallenge"
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    external: true